### ISSUE TITLE
MySQL doesn't automatically start when running the box

### ISSUE THREAD

**Issue by presidentnickson** [reddingwebpro/cognacbox#13]
Thanks for your work on this project !

I am having to manually ssh into vagrant and call `sudo service mysql start` when starting the machine (or indeed halting and upping again)

I've just upgraded from using scotchbox, and there wasn't a similar issue there.

**Comment by reddingwebpro** [comment]
Hmm, that is interesting. Which versions of vagrant and virtual box are you using? I am using 2.2.19 and 6.1.32 respectively. I just started a new box last week and it is bringing up MySQL just fine.

**Comment by presidentnickson** [comment]
I am using 2.2.10 and 6.1.14 - I will try to update them and see if that sorts it !

**Comment by presidentnickson** [comment]
Ok that seems to be working now :)
