### ISSUE TITLE
No box V2.3 available on Vagrantcloud

### ISSUE THREAD

**Issue by Franky1** [reddingwebpro/cognacbox#5]
This issue relates to the branch 2.3

The box image with version 2.3 cannot be downloaded from the Vagrant Cloud, although it is actually available there as version 2.3.

**Comment by reddingwebpro** [comment]
You're getting a bit ahead, 2.2 is the master branch and released and ready. 2.3 is still in testing.

**Comment by reddingwebpro** [comment]
The v2.3 was released as the master branch last month. Enjoy!
