### ISSUE TITLE
Version 2.3 showing up on SSH splash screen instead of version 3.0

### ISSUE THREAD

**Issue by pctutorialsonline** [reddingwebpro/cognacbox#8]
I'm 99% sure I'm running version 3 of Cognac Box, but the splash screen is showing 2.3. Anyway, don't stress, just a heads up.
![image](https://user-images.githubusercontent.com/58542184/111866245-3e7c6d00-89c0-11eb-89f0-f1a08035eb23.png)

**Comment by reddingwebpro** [comment]
Great catch, I'll fix it in the next release as it's simply cosmetic.

**Comment by reddingwebpro** [comment]
This is all fixed in the latest branch 3.0.1 - https://github.com/reddingwebpro/cognacbox
